### ISSUE TITLE
Extension Request

### ISSUE THREAD

**Issue by OshekharO** [Moleys/vbook-ext#6]
1. https://comrademao.com (no)
2. https://www.readwn.com (done)
3. https://www.mtlnovel.com
4. https://comick.app
5. https://comicastle.org
6. https://mangapill.com
7. https://daonovel.com
8. https://boxnovel.com
9. https://lnmtl.com

**Comment by Moleys** [comment]
Sorry I just saw this Request today.  #6 is already done, I will try #1-5.

**Comment by Moleys** [comment]
I will not do https://comrademao.com because it is directly translated by Google Translate, its source is Chinese text + English words
![image](https://user-images.githubusercontent.com/34809211/222340085-7c1a51b1-be56-442b-be67-d6bec0352065.png)

**Comment by Moleys** [comment]
https://www.readwn.com/ done

**Comment by OshekharO** [comment]
Thanks, can you send me vbook discord link

**Comment by OshekharO** [comment]
![Screenshot_2023-03-02-14-38-58-04_b0007220bda3443c86b5324d09eaa1db](https://user-images.githubusercontent.com/95137948/222383181-6e09c4a1-7a04-4413-9e4c-a2f1fcadcea7.jpg)

Hii I am not able to download your repository

**Comment by OshekharO** [comment]
Have added 3 more sources please check them out also if you like to add

**Comment by OshekharO** [comment]
How about making extensions for this https://github.com/miru-project/repo . it's in early stage so there are very few extensions but the app is good it supports : manga , light novel, movie, series, animes in single application.

@Moleys

**Comment by Moleys** [comment]
Wow, very promising, I will try when I can.

**Comment by OshekharO** [comment]
> Wow, very promising, I will try when I can.

Hmm thanks here is application group https://t.me/MiruChat
